version: '3.9'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: starter-mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
volumes:
  mssqldata:
